# Generated by Django 4.2.5 on 2023-09-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quote',
            field=models.CharField(default='quotes', max_length=100),
            preserve_default=False,
        ),
    ]
